SistemaWebEmpleado/Models/Empleado.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SistemaWebEmpleado.Validations;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaWebEmpleado.Models
{
    public class Empleado
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Este es un campo obligatorio")]
        [Column(TypeName = "varchar(50)")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Este es un campo obligatorio")]
        [Column(TypeName = "varchar(50)")]
        public string Apellido { get; set; }
        public int DNI { get; set; }

        [Required(ErrorMessage = "Este es un campo obligatorio")]
        [RegularExpression("^AA[0-9]{5}$", ErrorMessage = "Se aceptan 2 A al comienzo y cinco números")]
        public string Legajo { get; set; }
        [MayorDosmil]
        public DateTime FechaNacimiento { get; set; }
        [Required(ErrorMessage = "Este es un campo obligatorio")]
        [Column(TypeName = "varchar(50)")]
        public string Titulo { get; set; }
    }
}

SistemaWebEmpleado/Controllers/EmpleadoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaWebEmpleado.Data;
using SistemaWebEmpleado.Models;
using System.Collections.Generic;
using System.Linq;

namespace SistemaWebEmpleado.Controllers
{
    public class EmpleadoController : Controller
    {
        private readonly DbEmpleadoContext context;
        public EmpleadoController(DbEmpleadoContext context)
        {
            this.context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            //lista de empleados
            var empleados = context.Empleados.ToList();
            //enviar la lista a la vista.
            return View(empleados);
        }
        //---------AGREGAR
        //GET empleado/Create
        [HttpGet]
        public ActionResult Create()
        {
            Empleado empleado = new Empleado();

            return View("Create", empleado); // esto devuelve al cliente el html.
        }
        //POST empleado/Create
        [HttpPost]
        public ActionResult Create(Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                context.Empleados.Add(empleado); //guardas en memoria
                context.SaveChanges();// guardas en la db.
                return RedirectToAction("Index");
            }
            return View(empleado);
        }
       
        [HttpGet("titulo/{titulo}")]
        public ActionResult<IEnumerable<Empleado>> GetTitulo(string titulo)
        {
            var empleado = (from a in context.Empleados
                            where a.Titulo == titulo
                            select a).ToList();
            return View("GetTitulo", empleado);
        }
        
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Empleado empleado = context.Empleados.Find(id);
            if (empleado == null)
            {
                return NotFound();
            }
            else
            {
                return View("Delete", empleado);
            }
        }

        
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Empleado empleado = context.Empleados.Find(id);
            if (empleado == null)
            {
                return NotFound();
            }
            else
            {
                context.Empleados.Remove(empleado);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var empleado = context.Empleados.Find(id);
            if (empleado == null)
            {
                return NotFound();
            }
            else
            {

                return View("Details", empleado);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var empleado = context.Empleados.Find(id);
            if (empleado == null)
            {
                return NotFound();
            }
            else
            {
                return View("Edit", empleado);
            }
        }

        [HttpPost]
        [ActionName("Edit")]
        public ActionResult EditConfirmed(Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                context.Entry(empleado).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            else return View(empleado);
        }



    }

}

SistemaWebEmpleado/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;

namespace SistemaWebEmpleado.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Nombre = "Bienvenidos al sitio web!";
            ViewBag.Fecha = DateTime.Now.ToString();
            return View();
        }
    }
}

SistemaWebEmpleado/Views/Empleado/Create.cshtml
@model SistemaWebEmpleado.Models.Empleado
@{
    ViewData["Title"] = "Crear empleado";
}
@section SideBar{ 
    <p>Administración de empleados</p>
}
<h1>Registrar empleado</h1>
@using (Html.BeginForm("Create", "Empleado", FormMethod.Post))
{
    <p>
        @Html.LabelFor(model=>model.Nombre)
        @Html.TextBoxFor(model=>model.Nombre)
        @Html.ValidationMessageFor(model=>model.Nombre)
    </p>
    <p>
        @Html.LabelFor(model=>model.Apellido)
        @Html.TextBoxFor(model=>model.Apellido)
        @Html.ValidationMessageFor(model=>model.Apellido)
    </p>
    <p>
        @Html.LabelFor(model=>model.DNI)
        @Html.TextBoxFor(model=>model.DNI)
        @Html.ValidationMessageFor(model=>model.DNI)
    </p>
         <p>
        @Html.LabelFor(model=>model.Legajo)
        @Html.TextBoxFor(model=>model.Legajo)
        @Html.ValidationMessageFor(model=>model.Legajo)
        </p>
    <p>
        @Html.LabelFor(model=>model.FechaNacimiento)
        @Html.TextBoxFor(model=>model.FechaNacimiento)
        @Html.ValidationMessageFor(model=>model.FechaNacimiento)
    </p>
    <p>
        @Html.LabelFor(model=>model.Titulo)
        @Html.TextBoxFor(model=>model.Titulo)
        @Html.ValidationMessageFor(model=>model.Titulo)
    </p>

    <input type="submit" action="Create" />
    @Html.ActionLink("Volver", "Index", "Empleado")
}

SistemaWebEmpleado/Views/Empleado/Delete.cshtml
@model SistemaWebEmpleado.Models.Empleado

@{
    ViewData["Title"] = "Eliminar empleado";
}


<h2>@Model.Apellido</h2>
<p>¿Desea eliminar este empleado?</p>

@using (Html.BeginForm("Delete", "Empleado", FormMethod.Post))
{

        <div>
            <span>@Html.DisplayNameFor(model => model.Nombre)</span>
            <span>@Html.DisplayFor(model => model.Nombre)</span>
        </div>

        <div>
            <span>@Html.DisplayNameFor(model => model.Apellido)</span>
            <span>@Html.DisplayFor(model => model.Apellido)</span>
        </div>

        <div>
            <span>@Html.DisplayNameFor(model => model.DNI)</span>
            <span>@Html.DisplayFor(model => model.DNI)</span>
        </div>
        <div>
            <span>@Html.DisplayNameFor(model=>model.Legajo)</span>
            <span>@Html.DisplayFor(model=>model.Legajo)</span>
        </div>
        <div>
            <span>@Html.DisplayNameFor(model=>model.FechaNacimiento)</span>
            <span>@Html.DisplayFor(model=>model.FechaNacimiento)</span>
        </div>
        <div>
            <span>@Html.DisplayNameFor(model=>model.Titulo)</span>
            <span>@Html.DisplayFor(model=>model.Titulo)</span>
        </div>

        <input type="submit" action="Delete" />
    @Html.ActionLink("Volver", "Index", "Empleado")
}

SistemaWebEmpleado/Views/Empleado/Details.cshtml
@model SistemaWebEmpleado.Models.Empleado

@{
    ViewData["Title"] = "Detalle del empleado";
}

<h2>Detalle del empleado</h2>
@Html.ActionLink("Volver a Index", "Index", "Empleado")

<p>
    @Html.DisplayNameFor(model => model.Nombre)
    @Html.DisplayFor(model => model.Nombre)
</p>

<p>
    @Html.DisplayNameFor(model => model.Apellido)
    @Html.DisplayFor(model => model.Apellido)
</p><p>
    @Html.DisplayNameFor(model => model.DNI)
    @Html.DisplayFor(model => model.DNI)
</p><p>
    @Html.DisplayNameFor(model => model.Legajo)
    @Html.DisplayFor(model => model.Legajo)
</p><p>
    @Html.DisplayNameFor(model => model.FechaNacimiento)
    @Html.DisplayFor(model => model.FechaNacimiento)
</p><p>
    @Html.DisplayNameFor(model => model.Titulo)
    @Html.DisplayFor(model => model.Titulo)
</p>

SistemaWebEmpleado/Views/Empleado/Edit.cshtml
@model SistemaWebEmpleado.Models.Empleado
@{
    ViewData["Title"] = "Editar datos del empleado";
}
    <h2>Editar empleado</h2>
@using (Html.BeginForm("Edit", "Empleado", FormMethod.Post))
{
            <p>
        @Html.LabelFor(model=>model.Nombre)
        @Html.TextBoxFor(model=>model.Nombre)
        @Html.ValidationMessageFor(model=>model.Nombre)
            </p>
            <p>
        @Html.LabelFor(model=>model.Apellido)
        @Html.TextBoxFor(model=>model.Apellido)
        @Html.ValidationMessageFor(model=>model.Apellido)
            </p>
            <p>
        @Html.LabelFor(model=>model.DNI)
        @Html.TextBoxFor(model=>model.DNI)
        @Html.ValidationMessageFor(model=>model.DNI)
            </p>


<p>
        @Html.LabelFor(model=>model.Legajo)
        @Html.TextBoxFor(model=>model.Legajo)
        @Html.ValidationMessageFor(model=>model.Legajo)
            </p>
            <p>
        @Html.LabelFor(model=>model.FechaNacimiento)
        @Html.TextBoxFor(model=>model.FechaNacimiento)
        @Html.ValidationMessageFor(model=>model.FechaNacimiento)
            </p>
            <p>
        @Html.LabelFor(model=>model.Titulo)
        @Html.TextBoxFor(model=>model.Titulo)
        @Html.ValidationMessageFor(model=>model.Titulo)
            </p>

            <input type="submit" action="Edit"/>
    @Html.ActionLink("Volver","Index", "Empleado")

}

SistemaWebEmpleado/Views/Empleado/GetTitulo.cshtml
@model IEnumerable<SistemaWebEmpleado.Models.Empleado>
@{
    ViewData["Title"] = "Lista de empleados por título";
}
@section SideBar{
    <p>Administración de empleados</p>
}
@Html.ActionLink("Nuevo", "Create","Empleado")

<table>
    <tr>
        <th>@Html.DisplayNameFor(m=> m.Id)</th>
        <th>@Html.DisplayNameFor(m=> m.Nombre)</th>
        <th>@Html.DisplayNameFor(m=> m.Apellido)</th>
        <th>@Html.DisplayNameFor(m=> m.DNI)</th>
        <th>@Html.DisplayNameFor(m=> m.Legajo)</th>
        <th>@Html.DisplayNameFor(m=> m.FechaNacimiento)</th>
        <th>@Html.DisplayNameFor(m=> m.Titulo)</th>
    </tr>

    @foreach (var empleado in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(m=> empleado.Id)
            </td>
            <td>
                @Html.DisplayFor(m=> empleado.Nombre)
            </td>
            <td>
                @Html.DisplayFor(m=> empleado.Apellido)
            </td>
            <td>
                @Html.DisplayFor(m=> empleado.DNI)
            </td>
            <td>
                @Html.DisplayFor(m=> empleado.Legajo)
            </td>
            <td>
                @Html.DisplayFor(m=> empleado.FechaNacimiento)
            </td>
            <td>
                @Html.ActionLink(empleado.Titulo, "GetTitulo", "Empleado",new{titulo=empleado.Titulo})
            </td>
            @Html.ActionLink("Volver", "Index", "Empleado")
        </tr>
    }
</table>

SistemaWebEmpleado/Views/Empleado/Index.cshtml
@model IEnumerable<SistemaWebEmpleado.Models.Empleado>
<!--VA A RECIBIR UNA COLECCIÓN DE EMPLEADOS-->
@{
    ViewData["Title"] = "Index Empleado";
}
@section SideBar{
    <p>Administración de empleados</p>
}

@Html.ActionLink("Nuevo", "Create", "Empleado")
<table>
    <tr>
        <th>@Html.DisplayNameFor(model=>model.Id)</th>
        <th>@Html.DisplayNameFor(model=>model.Nombre)</th>
        <th>@Html.DisplayNameFor(model=>model.Apellido)</th>
        <th>@Html.DisplayNameFor(model=>model.DNI)</th>
        <th>@Html.DisplayNameFor(model=>model.Legajo)</th>
        <th>@Html.DisplayNameFor(model=>model.FechaNacimiento)</th>
        <th>@Html.DisplayNameFor(model=>model.Titulo)</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem=>item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem=>item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem=>item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem=>item.DNI)
            </td>
            <td>
                @Html.DisplayFor(modelItem=>item.Legajo)
            </td>
             <td>
                @Html.DisplayFor(modelItem=>item.FechaNacimiento)
            </td>
             <td>
                @Html.DisplayFor(modelItem=>item.Titulo)
            </td>
            <td>
                <!--esto es lo que recibe la action. id esta tal cual en la action-->
            @Html.ActionLink("Titulo", "GetTitulo", "Empleado", new{titulo=item.Titulo})
             
            </td>
                <td>
                @Html.ActionLink("Editar", "Edit", "Empleado",new{id=item.Id})
                @Html.ActionLink("Detalle", "Details", "Empleado",new{id=item.Id})
                @Html.ActionLink("Eliminar", "Delete", "Empleado",new{id=item.Id})
                </td>

        </tr>
    }
</table>

SistemaWebEmpleado/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index Home";
}
<h2>@ViewBag.Nombre</h2>
<h3>@ViewBag.Fecha</h3>

@Html.ActionLink("Ir a Empleados","Index","Empleado")

SistemaWebEmpleado/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/main.css" rel="stylesheet" />

</head>
<body>
    <header>
        <h1>SISTEMA Empleado</h1>

    </header>
    <aside>
        @if (IsSectionDefined("SideBar"))
        {
            @RenderSection("SideBar")
        }
        else
        {

                <h2>
                    Bienvenido
                    <img src="~/assets/smile.png" height="20px" width="20px"/>
                </h2>
        }
    </aside>
    <nav>
       <ul>
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("Empleado", "Index", "Empleado")</li>
        </ul>
    </nav>
    <main>
        @RenderBody()
    </main>
    <footer>
        <span>Info@Empleado.com</span>
    </footer>
</body>
</html>